/**
 * Extended Financial Document Template Library
 * Categories 6-12: Payroll, Tax, Assets, Investor, Audit, Forensic, SEC
 */

import { DocumentTemplate, DocumentCategory } from './document_templates';

// ============================================================================
// 6. PAYROLL & HR FINANCIALS
// ============================================================================

export const PAYROLL_HR_TEMPLATES: DocumentTemplate[] = [
  {
    id: 'payroll_register',
    name: 'Payroll Register',
    aliases: ['Payroll Journal', 'Pay Register'],
    category: 'payroll_hr',
    description: 'Detailed record of all payroll transactions for a pay period',
    file_naming_convention: '[ENTITY]_[YEAR]_PAY_Register_[PAYPERIOD]_[VERSION].xlsx',
    required_fields: [
      { name: 'pay_period_start', type: 'date', description: 'Pay period start', required: true },
      { name: 'pay_period_end', type: 'date', description: 'Pay period end', required: true },
      { name: 'pay_date', type: 'date', description: 'Pay date', required: true },
      { name: 'employee_id', type: 'string', description: 'Employee ID', required: true },
      { name: 'employee_name', type: 'string', description: 'Employee name', required: true },
      { name: 'gross_wages', type: 'currency', description: 'Gross wages', required: true },
      { name: 'federal_withholding', type: 'currency', description: 'Federal income tax withheld', required: true },
      { name: 'social_security_ee', type: 'currency', description: 'Social Security employee', required: true },
      { name: 'medicare_ee', type: 'currency', description: 'Medicare employee', required: true },
      { name: 'state_withholding', type: 'currency', description: 'State income tax withheld', required: true },
      { name: 'other_deductions', type: 'currency', description: 'Other deductions', required: true },
      { name: 'net_pay', type: 'currency', description: 'Net pay', required: true },
    ],
    optional_fields: [
      { name: 'overtime_hours', type: 'number', description: 'Overtime hours', required: false },
      { name: 'overtime_pay', type: 'currency', description: 'Overtime pay', required: false },
      { name: 'benefits_deductions', type: 'currency', description: 'Benefits deductions', required: false },
      { name: '401k_deductions', type: 'currency', description: '401k deductions', required: false },
    ],
    validation_rules: [
      {
        rule_id: 'PAY_NET',
        description: 'Net pay calculation',
        formula: 'net_pay === gross_wages - federal_withholding - ss_ee - med_ee - state - other',
        severity: 'critical',
        error_type: 'mathematical',
      },
      {
        rule_id: 'PAY_SS',
        description: 'Social Security = 6.2% of wages up to limit',
        formula: 'ss_ee === min(gross_wages, ss_limit) * 0.062',
        severity: 'high',
        error_type: 'mathematical',
      },
      {
        rule_id: 'PAY_MED',
        description: 'Medicare = 1.45% of wages',
        formula: 'medicare_ee === gross_wages * 0.0145',
        severity: 'high',
        error_type: 'mathematical',
      },
    ],
    error_checks: [
      {
        check_id: 'PAY_GHOST',
        name: 'Ghost Employee Detection',
        logic: 'Employee not in HR system or no timecards',
        red_flag_if_fails: true,
        severity: 'critical',
      },
      {
        check_id: 'PAY_DUP',
        name: 'Duplicate Payment',
        logic: 'Same employee paid twice in same period',
        red_flag_if_fails: true,
        severity: 'critical',
      },
    ],
    cross_references: [
      { document_type: 'timesheets', relationship: 'must_match', fields_to_compare: ['hours_worked'] },
      { document_type: 'form_941', relationship: 'should_reconcile', fields_to_compare: ['wages', 'withholding'] },
    ],
    retention_period: '7 years',
    regulatory_references: ['IRC 3401', 'FLSA'],
  },
  {
    id: 'timesheet',
    name: 'Timesheet',
    aliases: ['Time Card', 'Time Record'],
    category: 'payroll_hr',
    description: 'Record of employee hours worked',
    file_naming_convention: '[ENTITY]_[YEAR]_PAY_Timesheet_[EMPLOYEE]_[PERIOD]_[VERSION].xlsx',
    required_fields: [
      { name: 'employee_id', type: 'string', description: 'Employee ID', required: true },
      { name: 'employee_name', type: 'string', description: 'Employee name', required: true },
      { name: 'period_start', type: 'date', description: 'Period start', required: true },
      { name: 'period_end', type: 'date', description: 'Period end', required: true },
      { name: 'daily_hours', type: 'array', description: 'Hours by day', required: true },
      { name: 'total_regular_hours', type: 'number', description: 'Total regular hours', required: true },
      { name: 'total_overtime_hours', type: 'number', description: 'Total overtime hours', required: true },
      { name: 'supervisor_approval', type: 'string', description: 'Supervisor approval', required: true },
    ],
    optional_fields: [
      { name: 'project_codes', type: 'array', description: 'Project/job codes', required: false },
      { name: 'pto_hours', type: 'number', description: 'PTO hours', required: false },
    ],
    validation_rules: [
      {
        rule_id: 'TS_OT',
        description: 'Overtime = hours over 40/week or 8/day depending on state',
        formula: 'Check overtime calculation per applicable law',
        severity: 'high',
        error_type: 'compliance',
      },
    ],
    error_checks: [
      {
        check_id: 'TS_EXCESSIVE',
        name: 'Excessive Hours',
        logic: 'Hours > 60 per week should be flagged',
        red_flag_if_fails: false,
        severity: 'medium',
      },
    ],
    cross_references: [
      { document_type: 'payroll_register', relationship: 'must_match', fields_to_compare: ['hours'] },
    ],
    retention_period: '3 years (FLSA)',
    regulatory_references: ['FLSA 29 CFR 516'],
  },
  {
    id: 'form_w2',
    name: 'Form W-2',
    aliases: ['W-2', 'Wage and Tax Statement'],
    category: 'payroll_hr',
    description: 'Annual wage and tax statement for employees',
    file_naming_convention: '[ENTITY]_[YEAR]_TAX_W2_[EMPLOYEE]_[VERSION].pdf',
    required_fields: [
      { name: 'tax_year', type: 'string', description: 'Tax year', required: true },
      { name: 'employee_ssn', type: 'string', description: 'Employee SSN', required: true },
      { name: 'employee_name', type: 'string', description: 'Employee name', required: true },
      { name: 'employer_ein', type: 'string', description: 'Employer EIN', required: true },
      { name: 'box_1_wages', type: 'currency', description: 'Wages, tips, other comp', required: true },
      { name: 'box_2_fed_withheld', type: 'currency', description: 'Federal income tax withheld', required: true },
      { name: 'box_3_ss_wages', type: 'currency', description: 'Social Security wages', required: true },
      { name: 'box_4_ss_withheld', type: 'currency', description: 'Social Security tax withheld', required: true },
      { name: 'box_5_med_wages', type: 'currency', description: 'Medicare wages', required: true },
      { name: 'box_6_med_withheld', type: 'currency', description: 'Medicare tax withheld', required: true },
    ],
    optional_fields: [
      { name: 'box_12_codes', type: 'array', description: 'Box 12 coded amounts', required: false },
      { name: 'box_14_other', type: 'string', description: 'Box 14 other', required: false },
    ],
    validation_rules: [
      {
        rule_id: 'W2_SS',
        description: 'Box 4 = Box 3 * 6.2% (up to SS wage base)',
        formula: 'box_4 === min(box_3, ss_wage_base) * 0.062',
        severity: 'high',
        error_type: 'mathematical',
      },
      {
        rule_id: 'W2_MED',
        description: 'Box 6 = Box 5 * 1.45%',
        formula: 'box_6 === box_5 * 0.0145',
        severity: 'high',
        error_type: 'mathematical',
      },
    ],
    error_checks: [
      {
        check_id: 'W2_941_MATCH',
        name: 'W-2 to 941 Reconciliation',
        logic: 'Sum of all W-2s must match Form 941 totals',
        red_flag_if_fails: true,
        severity: 'critical',
      },
    ],
    cross_references: [
      { document_type: 'payroll_register', relationship: 'should_reconcile', fields_to_compare: ['annual_totals'] },
      { document_type: 'form_941', relationship: 'must_match', fields_to_compare: ['wages', 'withholding'] },
    ],
    retention_period: '4 years',
    regulatory_references: ['IRC 6051'],
  },
  {
    id: 'form_1099',
    name: 'Form 1099',
    aliases: ['1099-NEC', '1099-MISC'],
    category: 'payroll_hr',
    description: 'Information return for non-employee compensation',
    file_naming_convention: '[ENTITY]_[YEAR]_TAX_1099_[RECIPIENT]_[VERSION].pdf',
    required_fields: [
      { name: 'tax_year', type: 'string', description: 'Tax year', required: true },
      { name: 'form_type', type: 'string', description: '1099-NEC, 1099-MISC, etc.', required: true },
      { name: 'recipient_tin', type: 'string', description: 'Recipient TIN', required: true },
      { name: 'recipient_name', type: 'string', description: 'Recipient name', required: true },
      { name: 'payer_ein', type: 'string', description: 'Payer EIN', required: true },
      { name: 'amount', type: 'currency', description: 'Amount reported', required: true },
      { name: 'box_number', type: 'string', description: 'Reporting box', required: true },
    ],
    optional_fields: [
      { name: 'federal_withheld', type: 'currency', description: 'Federal tax withheld', required: false },
      { name: 'state_withheld', type: 'currency', description: 'State tax withheld', required: false },
    ],
    validation_rules: [
      {
        rule_id: '1099_THRESH',
        description: '1099-NEC required for payments >= $600',
        formula: 'amount >= 600 requires 1099',
        severity: 'high',
        error_type: 'compliance',
      },
    ],
    error_checks: [
      {
        check_id: '1099_W9',
        name: 'W-9 on File',
        logic: 'All 1099 recipients must have W-9',
        red_flag_if_fails: true,
        severity: 'high',
      },
    ],
    cross_references: [
      { document_type: 'ap_aging', relationship: 'should_reconcile', fields_to_compare: ['vendor_payments'] },
    ],
    retention_period: '4 years',
    regulatory_references: ['IRC 6041'],
  },
  {
    id: 'form_941',
    name: 'Form 941',
    aliases: ['Employer\'s Quarterly Federal Tax Return', 'Quarterly Payroll Tax Return'],
    category: 'payroll_hr',
    description: 'Quarterly report of employment taxes',
    file_naming_convention: '[ENTITY]_[YEAR]_TAX_941_Q[QUARTER]_[VERSION].pdf',
    required_fields: [
      { name: 'quarter', type: 'string', description: 'Quarter (Q1-Q4)', required: true },
      { name: 'year', type: 'string', description: 'Tax year', required: true },
      { name: 'number_of_employees', type: 'number', description: 'Number of employees', required: true },
      { name: 'total_wages', type: 'currency', description: 'Wages, tips, other comp', required: true },
      { name: 'federal_income_tax_withheld', type: 'currency', description: 'FIT withheld', required: true },
      { name: 'taxable_social_security_wages', type: 'currency', description: 'SS wages', required: true },
      { name: 'taxable_medicare_wages', type: 'currency', description: 'Medicare wages', required: true },
      { name: 'total_taxes', type: 'currency', description: 'Total taxes', required: true },
      { name: 'deposits_made', type: 'currency', description: 'Deposits made', required: true },
      { name: 'balance_due', type: 'currency', description: 'Balance due', required: true },
    ],
    optional_fields: [],
    validation_rules: [
      {
        rule_id: '941_FICA',
        description: 'FICA = SS wages * 12.4% + Med wages * 2.9%',
        formula: 'fica_taxes === (ss_wages * 0.124) + (med_wages * 0.029)',
        severity: 'critical',
        error_type: 'mathematical',
      },
      {
        rule_id: '941_TOTAL',
        description: 'Total taxes = FIT + FICA',
        formula: 'total_taxes === federal_income_tax + fica_taxes',
        severity: 'critical',
        error_type: 'mathematical',
      },
    ],
    error_checks: [
      {
        check_id: '941_DEPOSIT',
        name: 'Deposit Compliance',
        logic: 'Deposits made timely per deposit schedule',
        red_flag_if_fails: true,
        severity: 'high',
      },
    ],
    cross_references: [
      { document_type: 'payroll_register', relationship: 'must_match', fields_to_compare: ['quarterly_totals'] },
      { document_type: 'form_w2', relationship: 'should_reconcile', fields_to_compare: ['annual_totals'] },
    ],
    retention_period: '4 years',
    regulatory_references: ['IRC 3402', 'IRC 3101', 'IRC 3111'],
  },
  {
    id: 'benefits_expense_report',
    name: 'Benefits Expense Report',
    aliases: ['Employee Benefits Report'],
    category: 'payroll_hr',
    description: 'Summary of employee benefit costs',
    file_naming_convention: '[ENTITY]_[YEAR]_PAY_Benefits_[PERIOD]_[VERSION].xlsx',
    required_fields: [
      { name: 'period', type: 'string', description: 'Reporting period', required: true },
      { name: 'health_insurance', type: 'currency', description: 'Health insurance costs', required: true },
      { name: 'dental_insurance', type: 'currency', description: 'Dental insurance costs', required: true },
      { name: 'vision_insurance', type: 'currency', description: 'Vision insurance costs', required: true },
      { name: 'life_insurance', type: 'currency', description: 'Life insurance costs', required: true },
      { name: '401k_match', type: 'currency', description: '401k employer match', required: true },
      { name: 'other_benefits', type: 'currency', description: 'Other benefits', required: true },
      { name: 'total_benefits', type: 'currency', description: 'Total benefits expense', required: true },
    ],
    optional_fields: [],
    validation_rules: [
      {
        rule_id: 'BEN_TOTAL',
        description: 'Sum of benefits must equal total',
        formula: 'health + dental + vision + life + 401k + other === total',
        severity: 'high',
        error_type: 'mathematical',
      },
    ],
    error_checks: [],
    cross_references: [
      { document_type: 'general_ledger', relationship: 'must_match', fields_to_compare: ['benefits_expense'] },
    ],
    retention_period: '7 years',
  },
];

// ============================================================================
// 7. TAX DOCUMENTS
// ============================================================================

export const TAX_TEMPLATES: DocumentTemplate[] = [
  {
    id: 'form_1120',
    name: 'Form 1120',
    aliases: ['U.S. Corporation Income Tax Return', 'Corporate Tax Return'],
    category: 'tax',
    description: 'Annual income tax return for C corporations',
    file_naming_convention: '[ENTITY]_[YEAR]_TAX_1120_[VERSION].pdf',
    required_fields: [
      { name: 'tax_year', type: 'string', description: 'Tax year', required: true },
      { name: 'ein', type: 'string', description: 'Employer ID number', required: true },
      { name: 'gross_receipts', type: 'currency', description: 'Gross receipts', required: true },
      { name: 'cost_of_goods_sold', type: 'currency', description: 'COGS', required: true },
      { name: 'gross_profit', type: 'currency', description: 'Gross profit', required: true },
      { name: 'total_deductions', type: 'currency', description: 'Total deductions', required: true },
      { name: 'taxable_income', type: 'currency', description: 'Taxable income', required: true },
      { name: 'total_tax', type: 'currency', description: 'Total tax', required: true },
      { name: 'payments', type: 'currency', description: 'Estimated payments', required: true },
      { name: 'amount_owed', type: 'currency', description: 'Amount owed/overpayment', required: true },
    ],
    optional_fields: [
      { name: 'nol_deduction', type: 'currency', description: 'NOL deduction', required: false },
      { name: 'credits', type: 'currency', description: 'Tax credits', required: false },
    ],
    validation_rules: [
      {
        rule_id: '1120_GP',
        description: 'Gross profit = Gross receipts - COGS',
        formula: 'gross_profit === gross_receipts - cogs',
        severity: 'critical',
        error_type: 'mathematical',
      },
      {
        rule_id: '1120_TI',
        description: 'Taxable income calculation',
        formula: 'taxable_income === gross_profit + other_income - deductions',
        severity: 'critical',
        error_type: 'mathematical',
      },
      {
        rule_id: '1120_TAX',
        description: 'Tax = 21% of taxable income',
        formula: 'total_tax === taxable_income * 0.21',
        severity: 'critical',
        error_type: 'mathematical',
      },
    ],
    error_checks: [
      {
        check_id: '1120_M1',
        name: 'Book-Tax Reconciliation',
        logic: 'Schedule M-1 must reconcile book to tax income',
        red_flag_if_fails: true,
        severity: 'high',
      },
      {
        check_id: '1120_L',
        name: 'Balance Sheet Reconciliation',
        logic: 'Schedule L must match balance sheet',
        red_flag_if_fails: true,
        severity: 'high',
      },
    ],
    cross_references: [
      { document_type: 'income_statement', relationship: 'should_reconcile', fields_to_compare: ['book_income'] },
      { document_type: 'balance_sheet', relationship: 'must_match', fields_to_compare: ['schedule_l'] },
    ],
    retention_period: '7 years',
    regulatory_references: ['IRC 6012'],
  },
  {
    id: 'form_1065',
    name: 'Form 1065',
    aliases: ['U.S. Return of Partnership Income', 'Partnership Tax Return'],
    category: 'tax',
    description: 'Annual return for partnerships',
    file_naming_convention: '[ENTITY]_[YEAR]_TAX_1065_[VERSION].pdf',
    required_fields: [
      { name: 'tax_year', type: 'string', description: 'Tax year', required: true },
      { name: 'ein', type: 'string', description: 'Employer ID number', required: true },
      { name: 'gross_receipts', type: 'currency', description: 'Gross receipts', required: true },
      { name: 'ordinary_income', type: 'currency', description: 'Ordinary business income', required: true },
      { name: 'total_assets', type: 'currency', description: 'Total assets', required: true },
      { name: 'partners_capital', type: 'currency', description: 'Partners\' capital', required: true },
      { name: 'schedule_k', type: 'array', description: 'Schedule K items', required: true },
    ],
    optional_fields: [],
    validation_rules: [
      {
        rule_id: '1065_K',
        description: 'Schedule K must flow correctly',
        formula: 'Sum of K-1s must equal Schedule K totals',
        severity: 'critical',
        error_type: 'mathematical',
      },
    ],
    error_checks: [
      {
        check_id: '1065_CAP',
        name: 'Partner Capital Reconciliation',
        logic: 'Partner capital accounts must reconcile',
        red_flag_if_fails: true,
        severity: 'high',
      },
    ],
    cross_references: [
      { document_type: 'schedule_k1', relationship: 'must_match', fields_to_compare: ['partner_items'] },
    ],
    retention_period: '7 years',
    regulatory_references: ['IRC 6031'],
  },
  {
    id: 'form_1040',
    name: 'Form 1040',
    aliases: ['U.S. Individual Income Tax Return', 'Personal Tax Return'],
    category: 'tax',
    description: 'Annual income tax return for individuals',
    file_naming_convention: '[ENTITY]_[YEAR]_TAX_1040_[VERSION].pdf',
    required_fields: [
      { name: 'tax_year', type: 'string', description: 'Tax year', required: true },
      { name: 'ssn', type: 'string', description: 'Social Security number', required: true },
      { name: 'filing_status', type: 'string', description: 'Filing status', required: true },
      { name: 'total_income', type: 'currency', description: 'Total income', required: true },
      { name: 'adjusted_gross_income', type: 'currency', description: 'AGI', required: true },
      { name: 'deductions', type: 'currency', description: 'Standard or itemized deductions', required: true },
      { name: 'taxable_income', type: 'currency', description: 'Taxable income', required: true },
      { name: 'total_tax', type: 'currency', description: 'Total tax', required: true },
      { name: 'payments', type: 'currency', description: 'Total payments', required: true },
      { name: 'refund_or_owed', type: 'currency', description: 'Refund or amount owed', required: true },
    ],
    optional_fields: [],
    validation_rules: [
      {
        rule_id: '1040_TI',
        description: 'Taxable income = AGI - Deductions',
        formula: 'taxable_income === agi - deductions',
        severity: 'critical',
        error_type: 'mathematical',
      },
    ],
    error_checks: [],
    cross_references: [
      { document_type: 'form_w2', relationship: 'must_match', fields_to_compare: ['wages'] },
    ],
    retention_period: '7 years',
    regulatory_references: ['IRC 6012'],
  },
  {
    id: 'estimated_tax_payment',
    name: 'Estimated Tax Payment',
    aliases: ['Quarterly Estimated Tax', 'Form 1040-ES', 'Form 1120-W'],
    category: 'tax',
    description: 'Quarterly estimated tax payments',
    file_naming_convention: '[ENTITY]_[YEAR]_TAX_EstimatedPayment_Q[QUARTER]_[VERSION].pdf',
    required_fields: [
      { name: 'tax_year', type: 'string', description: 'Tax year', required: true },
      { name: 'quarter', type: 'string', description: 'Quarter', required: true },
      { name: 'due_date', type: 'date', description: 'Due date', required: true },
      { name: 'payment_date', type: 'date', description: 'Payment date', required: true },
      { name: 'amount', type: 'currency', description: 'Payment amount', required: true },
      { name: 'confirmation_number', type: 'string', description: 'Confirmation number', required: true },
    ],
    optional_fields: [],
    validation_rules: [
      {
        rule_id: 'EST_TIMELY',
        description: 'Payment must be timely',
        formula: 'payment_date <= due_date',
        severity: 'high',
        error_type: 'timing',
      },
    ],
    error_checks: [],
    cross_references: [
      { document_type: 'form_1120', relationship: 'should_reconcile', fields_to_compare: ['payments'] },
    ],
    retention_period: '7 years',
    regulatory_references: ['IRC 6654', 'IRC 6655'],
  },
  {
    id: 'property_tax_filing',
    name: 'Property Tax Filing',
    aliases: ['Property Tax Return', 'Real Estate Tax'],
    category: 'tax',
    description: 'Property tax filings and payments',
    file_naming_convention: '[ENTITY]_[YEAR]_TAX_PropertyTax_[PROPERTY]_[VERSION].pdf',
    required_fields: [
      { name: 'tax_year', type: 'string', description: 'Tax year', required: true },
      { name: 'property_address', type: 'string', description: 'Property address', required: true },
      { name: 'parcel_number', type: 'string', description: 'Parcel/APN number', required: true },
      { name: 'assessed_value', type: 'currency', description: 'Assessed value', required: true },
      { name: 'tax_rate', type: 'percentage', description: 'Tax rate', required: true },
      { name: 'tax_amount', type: 'currency', description: 'Tax amount', required: true },
      { name: 'due_date', type: 'date', description: 'Due date', required: true },
      { name: 'payment_date', type: 'date', description: 'Payment date', required: true },
    ],
    optional_fields: [],
    validation_rules: [
      {
        rule_id: 'PROP_CALC',
        description: 'Tax = Assessed value * Rate',
        formula: 'tax_amount === assessed_value * tax_rate',
        severity: 'high',
        error_type: 'mathematical',
      },
    ],
    error_checks: [],
    cross_references: [
      { document_type: 'fixed_asset_register', relationship: 'should_reconcile', fields_to_compare: ['properties'] },
    ],
    retention_period: '7 years',
  },
];

// ============================================================================
// 8. ASSETS & CAPITAL
// ============================================================================

export const ASSETS_CAPITAL_TEMPLATES: DocumentTemplate[] = [
  {
    id: 'fixed_asset_register',
    name: 'Fixed Asset Register',
    aliases: ['FA Register', 'Property Register', 'Asset Ledger'],
    category: 'assets_capital',
    description: 'Detailed listing of all fixed assets',
    file_naming_convention: '[ENTITY]_[YEAR]_FA_Register_[DATE]_[VERSION].xlsx',
    required_fields: [
      { name: 'asset_id', type: 'string', description: 'Asset ID/Tag number', required: true },
      { name: 'asset_description', type: 'string', description: 'Description', required: true },
      { name: 'asset_class', type: 'string', description: 'Asset class', required: true },
      { name: 'acquisition_date', type: 'date', description: 'Date acquired', required: true },
      { name: 'original_cost', type: 'currency', description: 'Original cost', required: true },
      { name: 'useful_life', type: 'number', description: 'Useful life (years)', required: true },
      { name: 'depreciation_method', type: 'string', description: 'Depreciation method', required: true },
      { name: 'accumulated_depreciation', type: 'currency', description: 'Accumulated depreciation', required: true },
      { name: 'net_book_value', type: 'currency', description: 'Net book value', required: true },
      { name: 'location', type: 'string', description: 'Physical location', required: true },
    ],
    optional_fields: [
      { name: 'serial_number', type: 'string', description: 'Serial number', required: false },
      { name: 'salvage_value', type: 'currency', description: 'Salvage value', required: false },
      { name: 'disposal_date', type: 'date', description: 'Disposal date', required: false },
    ],
    validation_rules: [
      {
        rule_id: 'FA_NBV',
        description: 'NBV = Cost - Accumulated Depreciation',
        formula: 'net_book_value === original_cost - accumulated_depreciation',
        severity: 'critical',
        error_type: 'mathematical',
      },
      {
        rule_id: 'FA_ACCUM',
        description: 'Accumulated depreciation cannot exceed cost',
        formula: 'accumulated_depreciation <= original_cost',
        severity: 'critical',
        error_type: 'valuation',
      },
    ],
    error_checks: [
      {
        check_id: 'FA_GHOST',
        name: 'Ghost Asset Detection',
        logic: 'Asset on books but cannot be physically verified',
        red_flag_if_fails: true,
        severity: 'high',
      },
    ],
    cross_references: [
      { document_type: 'balance_sheet', relationship: 'must_match', fields_to_compare: ['ppe_net'] },
      { document_type: 'depreciation_schedule', relationship: 'must_match', fields_to_compare: ['totals'] },
    ],
    retention_period: 'Life of asset + 7 years',
    regulatory_references: ['IRC 167', 'IRC 168', 'ASC 360'],
  },
  {
    id: 'depreciation_schedule',
    name: 'Depreciation Schedule',
    aliases: ['Depreciation Report', 'Amortization Schedule'],
    category: 'assets_capital',
    description: 'Schedule showing depreciation by asset',
    file_naming_convention: '[ENTITY]_[YEAR]_FA_Depreciation_[PERIOD]_[VERSION].xlsx',
    required_fields: [
      { name: 'asset_id', type: 'string', description: 'Asset ID', required: true },
      { name: 'asset_description', type: 'string', description: 'Description', required: true },
      { name: 'original_cost', type: 'currency', description: 'Original cost', required: true },
      { name: 'prior_accumulated', type: 'currency', description: 'Prior accumulated depreciation', required: true },
      { name: 'current_period_depreciation', type: 'currency', description: 'Current period depreciation', required: true },
      { name: 'ending_accumulated', type: 'currency', description: 'Ending accumulated depreciation', required: true },
      { name: 'net_book_value', type: 'currency', description: 'Ending NBV', required: true },
    ],
    optional_fields: [
      { name: 'book_depreciation', type: 'currency', description: 'Book depreciation', required: false },
      { name: 'tax_depreciation', type: 'currency', description: 'Tax depreciation', required: false },
      { name: 'section_179', type: 'currency', description: 'Section 179 expense', required: false },
      { name: 'bonus_depreciation', type: 'currency', description: 'Bonus depreciation', required: false },
    ],
    validation_rules: [
      {
        rule_id: 'DEP_ROLL',
        description: 'Accumulated depreciation rollforward',
        formula: 'ending_accumulated === prior_accumulated + current_period',
        severity: 'critical',
        error_type: 'mathematical',
      },
    ],
    error_checks: [],
    cross_references: [
      { document_type: 'fixed_asset_register', relationship: 'must_match', fields_to_compare: ['accumulated_depreciation'] },
      { document_type: 'income_statement', relationship: 'must_match', fields_to_compare: ['depreciation_expense'] },
    ],
    retention_period: 'Life of asset + 7 years',
    regulatory_references: ['IRC 167', 'IRC 168', 'IRC 179'],
  },
  {
    id: 'capex_approval',
    name: 'Capital Expenditure Approval',
    aliases: ['CapEx Request', 'Capital Project Approval'],
    category: 'assets_capital',
    description: 'Authorization for capital expenditure',
    file_naming_convention: '[ENTITY]_[YEAR]_FA_CapEx_[PROJECT]_[VERSION].pdf',
    required_fields: [
      { name: 'project_id', type: 'string', description: 'Project ID', required: true },
      { name: 'project_description', type: 'string', description: 'Description', required: true },
      { name: 'estimated_cost', type: 'currency', description: 'Estimated cost', required: true },
      { name: 'business_justification', type: 'string', description: 'Business justification', required: true },
      { name: 'requested_by', type: 'string', description: 'Requestor', required: true },
      { name: 'approved_by', type: 'string', description: 'Approver', required: true },
      { name: 'approval_date', type: 'date', description: 'Approval date', required: true },
      { name: 'expected_completion', type: 'date', description: 'Expected completion', required: true },
    ],
    optional_fields: [
      { name: 'roi_analysis', type: 'string', description: 'ROI analysis', required: false },
      { name: 'payback_period', type: 'number', description: 'Payback period (years)', required: false },
    ],
    validation_rules: [
      {
        rule_id: 'CAPEX_AUTH',
        description: 'Amount within approval authority',
        formula: 'estimated_cost <= approver_authority_limit',
        severity: 'high',
        error_type: 'authorization',
      },
    ],
    error_checks: [],
    cross_references: [
      { document_type: 'fixed_asset_register', relationship: 'supports', fields_to_compare: ['assets_added'] },
    ],
    retention_period: 'Life of asset + 7 years',
  },
  {
    id: 'lease_agreement',
    name: 'Lease Agreement',
    aliases: ['Operating Lease', 'Finance Lease', 'Rental Agreement'],
    category: 'assets_capital',
    description: 'Lease contract for property or equipment',
    file_naming_convention: '[ENTITY]_[YEAR]_LEASE_[PROPERTY]_[VERSION].pdf',
    required_fields: [
      { name: 'lease_id', type: 'string', description: 'Lease ID', required: true },
      { name: 'lessor', type: 'string', description: 'Lessor name', required: true },
      { name: 'asset_description', type: 'string', description: 'Leased asset', required: true },
      { name: 'lease_term', type: 'number', description: 'Lease term (months)', required: true },
      { name: 'commencement_date', type: 'date', description: 'Lease start date', required: true },
      { name: 'expiration_date', type: 'date', description: 'Lease end date', required: true },
      { name: 'monthly_payment', type: 'currency', description: 'Monthly payment', required: true },
      { name: 'total_lease_payments', type: 'currency', description: 'Total lease payments', required: true },
      { name: 'lease_classification', type: 'string', description: 'Operating/Finance', required: true },
    ],
    optional_fields: [
      { name: 'renewal_option', type: 'string', description: 'Renewal terms', required: false },
      { name: 'purchase_option', type: 'currency', description: 'Purchase option price', required: false },
      { name: 'right_of_use_asset', type: 'currency', description: 'ROU asset', required: false },
      { name: 'lease_liability', type: 'currency', description: 'Lease liability', required: false },
    ],
    validation_rules: [
      {
        rule_id: 'LEASE_TOTAL',
        description: 'Total payments = Monthly * Term',
        formula: 'total_lease_payments === monthly_payment * lease_term',
        severity: 'high',
        error_type: 'mathematical',
      },
    ],
    error_checks: [],
    cross_references: [
      { document_type: 'balance_sheet', relationship: 'should_reconcile', fields_to_compare: ['lease_liabilities'] },
    ],
    retention_period: 'Lease term + 7 years',
    regulatory_references: ['ASC 842'],
  },
  {
    id: 'loan_agreement',
    name: 'Loan Agreement',
    aliases: ['Credit Agreement', 'Note Payable', 'Debt Agreement'],
    category: 'assets_capital',
    description: 'Debt financing agreement',
    file_naming_convention: '[ENTITY]_[YEAR]_DEBT_[LENDER]_[VERSION].pdf',
    required_fields: [
      { name: 'loan_id', type: 'string', description: 'Loan ID', required: true },
      { name: 'lender', type: 'string', description: 'Lender name', required: true },
      { name: 'principal_amount', type: 'currency', description: 'Principal amount', required: true },
      { name: 'interest_rate', type: 'percentage', description: 'Interest rate', required: true },
      { name: 'origination_date', type: 'date', description: 'Origination date', required: true },
      { name: 'maturity_date', type: 'date', description: 'Maturity date', required: true },
      { name: 'payment_frequency', type: 'string', description: 'Payment frequency', required: true },
      { name: 'payment_amount', type: 'currency', description: 'Payment amount', required: true },
      { name: 'collateral', type: 'string', description: 'Collateral description', required: true },
    ],
    optional_fields: [
      { name: 'covenants', type: 'array', description: 'Financial covenants', required: false },
      { name: 'prepayment_penalty', type: 'string', description: 'Prepayment terms', required: false },
    ],
    validation_rules: [],
    error_checks: [
      {
        check_id: 'LOAN_COV',
        name: 'Covenant Compliance',
        logic: 'All financial covenants are being met',
        red_flag_if_fails: true,
        severity: 'high',
      },
    ],
    cross_references: [
      { document_type: 'debt_amortization_schedule', relationship: 'must_match', fields_to_compare: ['balances'] },
      { document_type: 'balance_sheet', relationship: 'must_match', fields_to_compare: ['debt_balances'] },
    ],
    retention_period: 'Loan term + 7 years',
  },
  {
    id: 'debt_amortization_schedule',
    name: 'Debt Amortization Schedule',
    aliases: ['Loan Amortization', 'Debt Schedule'],
    category: 'assets_capital',
    description: 'Schedule of debt payments and balances',
    file_naming_convention: '[ENTITY]_[YEAR]_DEBT_Amortization_[LENDER]_[VERSION].xlsx',
    required_fields: [
      { name: 'loan_id', type: 'string', description: 'Loan ID', required: true },
      { name: 'payment_number', type: 'number', description: 'Payment number', required: true },
      { name: 'payment_date', type: 'date', description: 'Payment date', required: true },
      { name: 'beginning_balance', type: 'currency', description: 'Beginning balance', required: true },
      { name: 'payment_amount', type: 'currency', description: 'Total payment', required: true },
      { name: 'principal', type: 'currency', description: 'Principal portion', required: true },
      { name: 'interest', type: 'currency', description: 'Interest portion', required: true },
      { name: 'ending_balance', type: 'currency', description: 'Ending balance', required: true },
    ],
    optional_fields: [],
    validation_rules: [
      {
        rule_id: 'AMORT_BAL',
        description: 'Ending = Beginning - Principal',
        formula: 'ending_balance === beginning_balance - principal',
        severity: 'critical',
        error_type: 'mathematical',
      },
      {
        rule_id: 'AMORT_PMT',
        description: 'Payment = Principal + Interest',
        formula: 'payment_amount === principal + interest',
        severity: 'critical',
        error_type: 'mathematical',
      },
    ],
    error_checks: [],
    cross_references: [
      { document_type: 'balance_sheet', relationship: 'must_match', fields_to_compare: ['debt_balances'] },
    ],
    retention_period: 'Loan term + 7 years',
  },
];

// ============================================================================
// 9. INVESTOR & EQUITY
// ============================================================================

export const INVESTOR_EQUITY_TEMPLATES: DocumentTemplate[] = [
  {
    id: 'cap_table',
    name: 'Capitalization Table',
    aliases: ['Cap Table', 'Equity Summary'],
    category: 'investor_equity',
    description: 'Summary of company ownership and equity securities',
    file_naming_convention: '[ENTITY]_[YEAR]_EQ_CapTable_[DATE]_[VERSION].xlsx',
    required_fields: [
      { name: 'shareholder_name', type: 'string', description: 'Shareholder name', required: true },
      { name: 'security_type', type: 'string', description: 'Common/Preferred/Options', required: true },
      { name: 'shares_authorized', type: 'number', description: 'Shares authorized', required: true },
      { name: 'shares_issued', type: 'number', description: 'Shares issued', required: true },
      { name: 'shares_outstanding', type: 'number', description: 'Shares outstanding', required: true },
      { name: 'ownership_percentage', type: 'percentage', description: 'Ownership %', required: true },
      { name: 'par_value', type: 'currency', description: 'Par value per share', required: true },
      { name: 'total_par_value', type: 'currency', description: 'Total par value', required: true },
    ],
    optional_fields: [
      { name: 'fully_diluted_ownership', type: 'percentage', description: 'Fully diluted %', required: false },
      { name: 'liquidation_preference', type: 'currency', description: 'Liquidation preference', required: false },
    ],
    validation_rules: [
      {
        rule_id: 'CAP_100',
        description: 'Ownership must sum to 100%',
        formula: 'sum(ownership_percentage) === 100%',
        severity: 'critical',
        error_type: 'mathematical',
      },
    ],
    error_checks: [],
    cross_references: [
      { document_type: 'balance_sheet', relationship: 'must_match', fields_to_compare: ['equity_accounts'] },
    ],
    retention_period: 'Permanent',
  },
  {
    id: 'share_certificate',
    name: 'Share Certificate',
    aliases: ['Stock Certificate'],
    category: 'investor_equity',
    description: 'Document evidencing share ownership',
    file_naming_convention: '[ENTITY]_[YEAR]_EQ_Certificate_[CERTNO]_[VERSION].pdf',
    required_fields: [
      { name: 'certificate_number', type: 'string', description: 'Certificate number', required: true },
      { name: 'shareholder_name', type: 'string', description: 'Shareholder name', required: true },
      { name: 'share_class', type: 'string', description: 'Share class', required: true },
      { name: 'number_of_shares', type: 'number', description: 'Number of shares', required: true },
      { name: 'issue_date', type: 'date', description: 'Issue date', required: true },
      { name: 'par_value', type: 'currency', description: 'Par value', required: true },
    ],
    optional_fields: [
      { name: 'transfer_restrictions', type: 'string', description: 'Transfer restrictions', required: false },
    ],
    validation_rules: [],
    error_checks: [],
    cross_references: [
      { document_type: 'cap_table', relationship: 'must_match', fields_to_compare: ['shares'] },
    ],
    retention_period: 'Permanent',
  },
  {
    id: 'stock_option_grant',
    name: 'Stock Option Grant',
    aliases: ['Option Grant', 'Equity Award'],
    category: 'investor_equity',
    description: 'Stock option grant agreement',
    file_naming_convention: '[ENTITY]_[YEAR]_EQ_OptionGrant_[GRANTEE]_[DATE]_[VERSION].pdf',
    required_fields: [
      { name: 'grant_id', type: 'string', description: 'Grant ID', required: true },
      { name: 'grantee_name', type: 'string', description: 'Grantee name', required: true },
      { name: 'grant_date', type: 'date', description: 'Grant date', required: true },
      { name: 'option_type', type: 'string', description: 'ISO/NSO', required: true },
      { name: 'shares_granted', type: 'number', description: 'Number of options', required: true },
      { name: 'exercise_price', type: 'currency', description: 'Exercise price', required: true },
      { name: 'fair_market_value', type: 'currency', description: 'FMV at grant', required: true },
      { name: 'vesting_schedule', type: 'string', description: 'Vesting schedule', required: true },
      { name: 'expiration_date', type: 'date', description: 'Expiration date', required: true },
    ],
    optional_fields: [
      { name: 'cliff_period', type: 'number', description: 'Cliff period (months)', required: false },
      { name: 'acceleration_terms', type: 'string', description: 'Acceleration provisions', required: false },
    ],
    validation_rules: [
      {
        rule_id: 'OPT_PRICE',
        description: 'Exercise price >= FMV for ISOs (IRC 422)',
        formula: 'exercise_price >= fair_market_value for ISO',
        severity: 'high',
        error_type: 'compliance',
      },
    ],
    error_checks: [],
    cross_references: [
      { document_type: 'cap_table', relationship: 'should_reconcile', fields_to_compare: ['options_pool'] },
    ],
    retention_period: 'Life of option + 7 years',
    regulatory_references: ['IRC 409A', 'IRC 422', 'ASC 718'],
  },
  {
    id: 'dividend_declaration',
    name: 'Dividend Declaration',
    aliases: ['Dividend Resolution'],
    category: 'investor_equity',
    description: 'Board resolution declaring dividend',
    file_naming_convention: '[ENTITY]_[YEAR]_EQ_Dividend_[DATE]_[VERSION].pdf',
    required_fields: [
      { name: 'declaration_date', type: 'date', description: 'Declaration date', required: true },
      { name: 'record_date', type: 'date', description: 'Record date', required: true },
      { name: 'payment_date', type: 'date', description: 'Payment date', required: true },
      { name: 'dividend_per_share', type: 'currency', description: 'Dividend per share', required: true },
      { name: 'total_dividend', type: 'currency', description: 'Total dividend amount', required: true },
      { name: 'share_class', type: 'string', description: 'Share class', required: true },
    ],
    optional_fields: [
      { name: 'dividend_type', type: 'string', description: 'Regular/Special', required: false },
    ],
    validation_rules: [
      {
        rule_id: 'DIV_CALC',
        description: 'Total = Per share * Shares outstanding',
        formula: 'total_dividend === dividend_per_share * shares_outstanding',
        severity: 'critical',
        error_type: 'mathematical',
      },
    ],
    error_checks: [],
    cross_references: [
      { document_type: 'statement_of_equity', relationship: 'must_match', fields_to_compare: ['dividends_declared'] },
    ],
    retention_period: '7 years',
  },
];

// ============================================================================
// 10. AUDIT & COMPLIANCE
// ============================================================================

export const AUDIT_COMPLIANCE_TEMPLATES: DocumentTemplate[] = [
  {
    id: 'audit_report',
    name: 'Audit Report',
    aliases: ['Auditor\'s Report', 'Independent Auditor\'s Report'],
    category: 'audit_compliance',
    description: 'Independent auditor\'s opinion on financial statements',
    file_naming_convention: '[ENTITY]_[YEAR]_AUDIT_Report_[VERSION].pdf',
    required_fields: [
      { name: 'audit_firm', type: 'string', description: 'Audit firm name', required: true },
      { name: 'report_date', type: 'date', description: 'Report date', required: true },
      { name: 'fiscal_year_end', type: 'date', description: 'Fiscal year end', required: true },
      { name: 'opinion_type', type: 'string', description: 'Unqualified/Qualified/Adverse/Disclaimer', required: true },
      { name: 'scope_paragraph', type: 'string', description: 'Scope of audit', required: true },
      { name: 'opinion_paragraph', type: 'string', description: 'Opinion', required: true },
    ],
    optional_fields: [
      { name: 'emphasis_of_matter', type: 'string', description: 'Emphasis paragraphs', required: false },
      { name: 'key_audit_matters', type: 'array', description: 'Key audit matters', required: false },
    ],
    validation_rules: [],
    error_checks: [
      {
        check_id: 'AUD_QUAL',
        name: 'Qualified Opinion',
        logic: 'Qualified, adverse, or disclaimer opinion issued',
        red_flag_if_fails: true,
        severity: 'critical',
      },
    ],
    cross_references: [],
    retention_period: 'Permanent',
    regulatory_references: ['GAAS', 'PCAOB Standards'],
  },
  {
    id: 'management_representation_letter',
    name: 'Management Representation Letter',
    aliases: ['Rep Letter', 'Management Letter'],
    category: 'audit_compliance',
    description: 'Written representations from management to auditor',
    file_naming_convention: '[ENTITY]_[YEAR]_AUDIT_RepLetter_[VERSION].pdf',
    required_fields: [
      { name: 'date', type: 'date', description: 'Letter date', required: true },
      { name: 'addressed_to', type: 'string', description: 'Audit firm', required: true },
      { name: 'representations', type: 'array', description: 'List of representations', required: true },
      { name: 'signed_by', type: 'string', description: 'Signatory (CEO/CFO)', required: true },
    ],
    optional_fields: [],
    validation_rules: [],
    error_checks: [],
    cross_references: [],
    retention_period: 'Permanent',
  },
  {
    id: 'internal_control_report',
    name: 'Internal Control Report',
    aliases: ['IC Report', 'Controls Assessment'],
    category: 'audit_compliance',
    description: 'Assessment of internal controls over financial reporting',
    file_naming_convention: '[ENTITY]_[YEAR]_AUDIT_ICReport_[VERSION].pdf',
    required_fields: [
      { name: 'assessment_date', type: 'date', description: 'Assessment date', required: true },
      { name: 'framework', type: 'string', description: 'Framework used (COSO, etc.)', required: true },
      { name: 'scope', type: 'string', description: 'Scope of assessment', required: true },
      { name: 'conclusion', type: 'string', description: 'Conclusion', required: true },
      { name: 'deficiencies', type: 'array', description: 'Control deficiencies', required: true },
    ],
    optional_fields: [
      { name: 'material_weaknesses', type: 'array', description: 'Material weaknesses', required: false },
      { name: 'significant_deficiencies', type: 'array', description: 'Significant deficiencies', required: false },
    ],
    validation_rules: [],
    error_checks: [
      {
        check_id: 'IC_MW',
        name: 'Material Weakness',
        logic: 'Material weakness identified in ICFR',
        red_flag_if_fails: true,
        severity: 'critical',
      },
    ],
    cross_references: [],
    retention_period: '7 years',
    regulatory_references: ['SOX 404', 'COSO Framework'],
  },
  {
    id: 'sox_testing_report',
    name: 'SOX Testing Report',
    aliases: ['SOX 404 Testing', 'Controls Testing'],
    category: 'audit_compliance',
    description: 'Documentation of SOX 404 control testing',
    file_naming_convention: '[ENTITY]_[YEAR]_AUDIT_SOXTesting_[VERSION].xlsx',
    required_fields: [
      { name: 'control_id', type: 'string', description: 'Control ID', required: true },
      { name: 'control_description', type: 'string', description: 'Control description', required: true },
      { name: 'control_owner', type: 'string', description: 'Control owner', required: true },
      { name: 'control_frequency', type: 'string', description: 'Frequency', required: true },
      { name: 'test_procedure', type: 'string', description: 'Test procedure', required: true },
      { name: 'sample_size', type: 'number', description: 'Sample size', required: true },
      { name: 'exceptions', type: 'number', description: 'Number of exceptions', required: true },
      { name: 'test_conclusion', type: 'string', description: 'Effective/Ineffective', required: true },
      { name: 'tester', type: 'string', description: 'Tester name', required: true },
      { name: 'test_date', type: 'date', description: 'Test date', required: true },
    ],
    optional_fields: [],
    validation_rules: [],
    error_checks: [],
    cross_references: [],
    retention_period: '7 years',
    regulatory_references: ['SOX 404'],
  },
  {
    id: 'risk_assessment',
    name: 'Risk Assessment',
    aliases: ['Risk Matrix', 'Risk Register'],
    category: 'audit_compliance',
    description: 'Assessment of financial and operational risks',
    file_naming_convention: '[ENTITY]_[YEAR]_AUDIT_RiskAssessment_[VERSION].xlsx',
    required_fields: [
      { name: 'risk_id', type: 'string', description: 'Risk ID', required: true },
      { name: 'risk_description', type: 'string', description: 'Risk description', required: true },
      { name: 'risk_category', type: 'string', description: 'Category', required: true },
      { name: 'likelihood', type: 'string', description: 'Likelihood (H/M/L)', required: true },
      { name: 'impact', type: 'string', description: 'Impact (H/M/L)', required: true },
      { name: 'inherent_risk', type: 'string', description: 'Inherent risk rating', required: true },
      { name: 'mitigating_controls', type: 'array', description: 'Mitigating controls', required: true },
      { name: 'residual_risk', type: 'string', description: 'Residual risk rating', required: true },
      { name: 'risk_owner', type: 'string', description: 'Risk owner', required: true },
    ],
    optional_fields: [],
    validation_rules: [],
    error_checks: [],
    cross_references: [],
    retention_period: '7 years',
  },
];

// ============================================================================
// 11. FORENSIC / INVESTIGATION FILES
// ============================================================================

export const FORENSIC_INVESTIGATION_TEMPLATES: DocumentTemplate[] = [
  {
    id: 'transaction_tracing_report',
    name: 'Transaction Tracing Report',
    aliases: ['Fund Tracing', 'Asset Tracing'],
    category: 'forensic_investigation',
    description: 'Detailed tracing of transactions through accounts',
    file_naming_convention: '[ENTITY]_[YEAR]_FORENSIC_TxnTracing_[CASE]_[VERSION].xlsx',
    required_fields: [
      { name: 'case_id', type: 'string', description: 'Case ID', required: true },
      { name: 'trace_date', type: 'date', description: 'Trace date', required: true },
      { name: 'source_account', type: 'string', description: 'Source account', required: true },
      { name: 'destination_account', type: 'string', description: 'Destination account', required: true },
      { name: 'transaction_date', type: 'date', description: 'Transaction date', required: true },
      { name: 'amount', type: 'currency', description: 'Amount', required: true },
      { name: 'description', type: 'string', description: 'Transaction description', required: true },
      { name: 'supporting_documents', type: 'array', description: 'Supporting docs', required: true },
      { name: 'findings', type: 'string', description: 'Findings', required: true },
    ],
    optional_fields: [
      { name: 'red_flags', type: 'array', description: 'Red flags identified', required: false },
    ],
    validation_rules: [],
    error_checks: [],
    cross_references: [
      { document_type: 'bank_statement', relationship: 'must_match', fields_to_compare: ['transactions'] },
    ],
    retention_period: 'Case duration + 7 years',
  },
  {
    id: 'source_use_of_funds',
    name: 'Source and Use of Funds',
    aliases: ['Funds Flow Analysis', 'Cash Flow Tracing'],
    category: 'forensic_investigation',
    description: 'Analysis of fund sources and uses',
    file_naming_convention: '[ENTITY]_[YEAR]_FORENSIC_SourceUse_[CASE]_[VERSION].xlsx',
    required_fields: [
      { name: 'case_id', type: 'string', description: 'Case ID', required: true },
      { name: 'period', type: 'string', description: 'Analysis period', required: true },
      { name: 'sources_of_funds', type: 'array', description: 'All fund sources', required: true },
      { name: 'uses_of_funds', type: 'array', description: 'All fund uses', required: true },
      { name: 'total_sources', type: 'currency', description: 'Total sources', required: true },
      { name: 'total_uses', type: 'currency', description: 'Total uses', required: true },
      { name: 'variance', type: 'currency', description: 'Unexplained variance', required: true },
    ],
    optional_fields: [],
    validation_rules: [
      {
        rule_id: 'SUF_BAL',
        description: 'Sources should approximately equal uses',
        formula: 'abs(total_sources - total_uses) <= threshold',
        severity: 'high',
        error_type: 'completeness',
      },
    ],
    error_checks: [
      {
        check_id: 'SUF_VAR',
        name: 'Unexplained Variance',
        logic: 'Significant unexplained variance in funds',
        red_flag_if_fails: true,
        severity: 'critical',
      },
    ],
    cross_references: [],
    retention_period: 'Case duration + 7 years',
  },
  {
    id: 'related_party_transaction_analysis',
    name: 'Related Party Transaction Analysis',
    aliases: ['RPT Analysis', 'Intercompany Analysis'],
    category: 'forensic_investigation',
    description: 'Analysis of related party transactions',
    file_naming_convention: '[ENTITY]_[YEAR]_FORENSIC_RPT_[CASE]_[VERSION].xlsx',
    required_fields: [
      { name: 'case_id', type: 'string', description: 'Case ID', required: true },
      { name: 'related_party', type: 'string', description: 'Related party name', required: true },
      { name: 'relationship', type: 'string', description: 'Nature of relationship', required: true },
      { name: 'transactions', type: 'array', description: 'Transaction list', required: true },
      { name: 'total_amount', type: 'currency', description: 'Total transaction amount', required: true },
      { name: 'arms_length_assessment', type: 'string', description: 'Arms length determination', required: true },
      { name: 'findings', type: 'string', description: 'Findings', required: true },
    ],
    optional_fields: [
      { name: 'market_comparables', type: 'array', description: 'Comparable transactions', required: false },
    ],
    validation_rules: [],
    error_checks: [
      {
        check_id: 'RPT_AL',
        name: 'Non-Arms Length',
        logic: 'Transaction not at arms length terms',
        red_flag_if_fails: true,
        severity: 'high',
      },
    ],
    cross_references: [],
    retention_period: 'Case duration + 7 years',
    regulatory_references: ['IRC 267', 'IRC 482', 'ASC 850'],
  },
  {
    id: 'fraud_examination_report',
    name: 'Fraud Examination Report',
    aliases: ['Fraud Report', 'Investigation Report'],
    category: 'forensic_investigation',
    description: 'Report documenting fraud examination findings',
    file_naming_convention: '[ENTITY]_[YEAR]_FORENSIC_FraudReport_[CASE]_[VERSION].pdf',
    required_fields: [
      { name: 'case_id', type: 'string', description: 'Case ID', required: true },
      { name: 'report_date', type: 'date', description: 'Report date', required: true },
      { name: 'prepared_by', type: 'string', description: 'Examiner', required: true },
      { name: 'engagement_scope', type: 'string', description: 'Scope of engagement', required: true },
      { name: 'procedures_performed', type: 'array', description: 'Procedures performed', required: true },
      { name: 'findings', type: 'array', description: 'Findings', required: true },
      { name: 'loss_quantification', type: 'currency', description: 'Estimated loss', required: true },
      { name: 'recommendations', type: 'array', description: 'Recommendations', required: true },
    ],
    optional_fields: [
      { name: 'subjects', type: 'array', description: 'Subjects of investigation', required: false },
      { name: 'exhibits', type: 'array', description: 'Supporting exhibits', required: false },
    ],
    validation_rules: [],
    error_checks: [],
    cross_references: [],
    retention_period: 'Case duration + 7 years',
  },
  {
    id: 'aml_kyc_documentation',
    name: 'AML/KYC Documentation',
    aliases: ['Customer Due Diligence', 'Know Your Customer'],
    category: 'forensic_investigation',
    description: 'Anti-money laundering and customer identification documentation',
    file_naming_convention: '[ENTITY]_[YEAR]_AML_[CUSTOMER]_[VERSION].pdf',
    required_fields: [
      { name: 'customer_id', type: 'string', description: 'Customer ID', required: true },
      { name: 'customer_name', type: 'string', description: 'Customer name', required: true },
      { name: 'customer_type', type: 'string', description: 'Individual/Entity', required: true },
      { name: 'identification_documents', type: 'array', description: 'ID documents', required: true },
      { name: 'beneficial_owners', type: 'array', description: 'Beneficial owners', required: true },
      { name: 'risk_rating', type: 'string', description: 'Risk rating (H/M/L)', required: true },
      { name: 'source_of_funds', type: 'string', description: 'Source of funds', required: true },
      { name: 'review_date', type: 'date', description: 'Last review date', required: true },
    ],
    optional_fields: [
      { name: 'pep_status', type: 'boolean', description: 'Politically exposed person', required: false },
      { name: 'sanctions_check', type: 'string', description: 'Sanctions screening result', required: false },
    ],
    validation_rules: [],
    error_checks: [
      {
        check_id: 'AML_PEP',
        name: 'PEP Status',
        logic: 'Customer is politically exposed person',
        red_flag_if_fails: false,
        severity: 'high',
      },
      {
        check_id: 'AML_SANC',
        name: 'Sanctions Hit',
        logic: 'Customer on sanctions list',
        red_flag_if_fails: true,
        severity: 'critical',
      },
    ],
    cross_references: [],
    retention_period: '5 years after relationship ends',
    regulatory_references: ['BSA', 'USA PATRIOT Act', 'FinCEN Requirements'],
  },
];

// ============================================================================
// 12. SEC & PUBLIC COMPANY FILINGS
// ============================================================================

export const SEC_FILINGS_TEMPLATES: DocumentTemplate[] = [
  {
    id: 'form_10k',
    name: 'Form 10-K',
    aliases: ['10-K', 'Annual Report'],
    category: 'sec_filings',
    description: 'Annual report filed with SEC',
    file_naming_convention: '[ENTITY]_[YEAR]_SEC_10K_[VERSION].pdf',
    required_fields: [
      { name: 'fiscal_year_end', type: 'date', description: 'Fiscal year end', required: true },
      { name: 'filing_date', type: 'date', description: 'Filing date', required: true },
      { name: 'cik', type: 'string', description: 'CIK number', required: true },
      { name: 'business_description', type: 'string', description: 'Item 1 - Business', required: true },
      { name: 'risk_factors', type: 'string', description: 'Item 1A - Risk Factors', required: true },
      { name: 'mda', type: 'string', description: 'Item 7 - MD&A', required: true },
      { name: 'financial_statements', type: 'string', description: 'Item 8 - Financial Statements', required: true },
      { name: 'ceo_certification', type: 'boolean', description: 'CEO 302 Certification', required: true },
      { name: 'cfo_certification', type: 'boolean', description: 'CFO 302 Certification', required: true },
    ],
    optional_fields: [],
    validation_rules: [],
    error_checks: [],
    cross_references: [
      { document_type: 'audit_report', relationship: 'must_match', fields_to_compare: ['opinion'] },
    ],
    retention_period: 'Permanent',
    regulatory_references: ['Securities Exchange Act Section 13', 'Regulation S-K', 'Regulation S-X'],
  },
  {
    id: 'form_10q',
    name: 'Form 10-Q',
    aliases: ['10-Q', 'Quarterly Report'],
    category: 'sec_filings',
    description: 'Quarterly report filed with SEC',
    file_naming_convention: '[ENTITY]_[YEAR]_SEC_10Q_Q[QUARTER]_[VERSION].pdf',
    required_fields: [
      { name: 'quarter', type: 'string', description: 'Fiscal quarter', required: true },
      { name: 'period_end', type: 'date', description: 'Period end date', required: true },
      { name: 'filing_date', type: 'date', description: 'Filing date', required: true },
      { name: 'financial_statements', type: 'string', description: 'Part I - Financial Statements', required: true },
      { name: 'mda', type: 'string', description: 'Part I - MD&A', required: true },
      { name: 'ceo_certification', type: 'boolean', description: 'CEO 302 Certification', required: true },
      { name: 'cfo_certification', type: 'boolean', description: 'CFO 302 Certification', required: true },
    ],
    optional_fields: [],
    validation_rules: [],
    error_checks: [],
    cross_references: [],
    retention_period: 'Permanent',
    regulatory_references: ['Securities Exchange Act Section 13'],
  },
  {
    id: 'form_8k',
    name: 'Form 8-K',
    aliases: ['8-K', 'Current Report'],
    category: 'sec_filings',
    description: 'Current report for material events',
    file_naming_convention: '[ENTITY]_[YEAR]_SEC_8K_[DATE]_[VERSION].pdf',
    required_fields: [
      { name: 'filing_date', type: 'date', description: 'Filing date', required: true },
      { name: 'event_date', type: 'date', description: 'Event date', required: true },
      { name: 'item_number', type: 'string', description: 'Item number(s) reported', required: true },
      { name: 'event_description', type: 'string', description: 'Event description', required: true },
    ],
    optional_fields: [
      { name: 'exhibits', type: 'array', description: 'Exhibit list', required: false },
    ],
    validation_rules: [
      {
        rule_id: '8K_TIME',
        description: 'Filed within 4 business days of event',
        formula: 'filing_date <= event_date + 4 business days',
        severity: 'high',
        error_type: 'timing',
      },
    ],
    error_checks: [],
    cross_references: [],
    retention_period: 'Permanent',
    regulatory_references: ['Securities Exchange Act Section 13'],
  },
  {
    id: 'form_s1',
    name: 'Form S-1',
    aliases: ['S-1', 'Registration Statement', 'IPO Registration'],
    category: 'sec_filings',
    description: 'Registration statement for IPO',
    file_naming_convention: '[ENTITY]_[YEAR]_SEC_S1_[VERSION].pdf',
    required_fields: [
      { name: 'filing_date', type: 'date', description: 'Initial filing date', required: true },
      { name: 'prospectus', type: 'string', description: 'Prospectus', required: true },
      { name: 'use_of_proceeds', type: 'string', description: 'Use of proceeds', required: true },
      { name: 'shares_offered', type: 'number', description: 'Shares to be offered', required: true },
      { name: 'offering_price_range', type: 'string', description: 'Price range', required: true },
      { name: 'underwriters', type: 'array', description: 'Underwriter list', required: true },
    ],
    optional_fields: [],
    validation_rules: [],
    error_checks: [],
    cross_references: [],
    retention_period: 'Permanent',
    regulatory_references: ['Securities Act Section 5'],
  },
  {
    id: 'def_14a',
    name: 'DEF 14A',
    aliases: ['Proxy Statement', 'Definitive Proxy'],
    category: 'sec_filings',
    description: 'Definitive proxy statement',
    file_naming_convention: '[ENTITY]_[YEAR]_SEC_DEF14A_[VERSION].pdf',
    required_fields: [
      { name: 'filing_date', type: 'date', description: 'Filing date', required: true },
      { name: 'meeting_date', type: 'date', description: 'Annual meeting date', required: true },
      { name: 'record_date', type: 'date', description: 'Record date', required: true },
      { name: 'director_nominees', type: 'array', description: 'Director nominees', required: true },
      { name: 'executive_compensation', type: 'string', description: 'Executive compensation', required: true },
      { name: 'proposals', type: 'array', description: 'Shareholder proposals', required: true },
    ],
    optional_fields: [],
    validation_rules: [],
    error_checks: [],
    cross_references: [],
    retention_period: 'Permanent',
    regulatory_references: ['Securities Exchange Act Section 14'],
  },
  {
    id: 'schedule_13d',
    name: 'Schedule 13D',
    aliases: ['13D', 'Beneficial Ownership Report'],
    category: 'sec_filings',
    description: 'Beneficial ownership report for 5%+ holders',
    file_naming_convention: '[ENTITY]_[YEAR]_SEC_13D_[FILER]_[VERSION].pdf',
    required_fields: [
      { name: 'filing_date', type: 'date', description: 'Filing date', required: true },
      { name: 'filer_name', type: 'string', description: 'Filer name', required: true },
      { name: 'issuer_name', type: 'string', description: 'Issuer name', required: true },
      { name: 'shares_beneficially_owned', type: 'number', description: 'Shares owned', required: true },
      { name: 'percentage_of_class', type: 'percentage', description: 'Ownership %', required: true },
      { name: 'purpose_of_transaction', type: 'string', description: 'Purpose', required: true },
    ],
    optional_fields: [],
    validation_rules: [
      {
        rule_id: '13D_TIME',
        description: 'Filed within 10 days of crossing 5%',
        formula: 'filing_date <= threshold_date + 10 days',
        severity: 'high',
        error_type: 'timing',
      },
    ],
    error_checks: [],
    cross_references: [],
    retention_period: 'Permanent',
    regulatory_references: ['Securities Exchange Act Section 13(d)'],
  },
  {
    id: 'form_4',
    name: 'Form 4',
    aliases: ['Insider Trading Report', 'Statement of Changes'],
    category: 'sec_filings',
    description: 'Insider trading report',
    file_naming_convention: '[ENTITY]_[YEAR]_SEC_Form4_[INSIDER]_[DATE]_[VERSION].pdf',
    required_fields: [
      { name: 'filing_date', type: 'date', description: 'Filing date', required: true },
      { name: 'insider_name', type: 'string', description: 'Insider name', required: true },
      { name: 'relationship', type: 'string', description: 'Relationship to issuer', required: true },
      { name: 'issuer_name', type: 'string', description: 'Issuer name', required: true },
      { name: 'transaction_date', type: 'date', description: 'Transaction date', required: true },
      { name: 'transaction_code', type: 'string', description: 'Transaction code', required: true },
      { name: 'shares_acquired', type: 'number', description: 'Shares acquired/disposed', required: true },
      { name: 'price_per_share', type: 'currency', description: 'Price per share', required: true },
      { name: 'shares_owned_after', type: 'number', description: 'Shares owned after', required: true },
    ],
    optional_fields: [],
    validation_rules: [
      {
        rule_id: 'FORM4_TIME',
        description: 'Filed within 2 business days of transaction',
        formula: 'filing_date <= transaction_date + 2 business days',
        severity: 'high',
        error_type: 'timing',
      },
    ],
    error_checks: [],
    cross_references: [],
    retention_period: 'Permanent',
    regulatory_references: ['Securities Exchange Act Section 16'],
  },
];

// ============================================================================
// COMBINED EXTENDED TEMPLATES
// ============================================================================

export const EXTENDED_DOCUMENT_TEMPLATES: Record<string, DocumentTemplate[]> = {
  payroll_hr: PAYROLL_HR_TEMPLATES,
  tax: TAX_TEMPLATES,
  assets_capital: ASSETS_CAPITAL_TEMPLATES,
  investor_equity: INVESTOR_EQUITY_TEMPLATES,
  audit_compliance: AUDIT_COMPLIANCE_TEMPLATES,
  forensic_investigation: FORENSIC_INVESTIGATION_TEMPLATES,
  sec_filings: SEC_FILINGS_TEMPLATES,
};

// Export total count
export function getTotalTemplateCount(): number {
  const extendedCount = Object.values(EXTENDED_DOCUMENT_TEMPLATES)
    .reduce((sum, arr) => sum + arr.length, 0);
  return extendedCount;
}

// Get all extended templates as flat array
export function getAllExtendedTemplates(): DocumentTemplate[] {
  return Object.values(EXTENDED_DOCUMENT_TEMPLATES).flat();
}
